### ISSUE TITLE
but this error 

### ISSUE THREAD

**Issue by thaifani** [DevExpress-Examples/how-to-convert-and-then-print-an-aspxgridview-by-using-the-xtrareport-e4476#1]
ClearFilterButton' property cannot be set declaratively.

**Comment by outsidergiant** [comment]
Hi,

This issue occurs due to the change described at [BC2948: ASPxGridView - Changes in API, style settings and element rendering](https://www.devexpress.com/Support/Center/VersionHistory?TechnologyName=.NET&PlatformName=AllPlatforms&ProductName=AllProducts&VersionHistoryItemsType=BreakingChanges&StartBuildName=15.1.3&EndBuildName=15.1.3&version-mode=single-mode#BC2948). To resolve this issue, use the [ShowClearFilterButton](https://documentation.devexpress.com/AspNet/DevExpress.Web.GridViewCommandColumn.ShowClearFilterButton.property) property instead. I also created a new branch for v15.1.3 and newer where this approach is used.

**Comment by thaifani** [comment]
oh thanks
